-- TODO:
-- 코드를 입력하세요
-- solve 1
SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS ins, ANIMAL_OUTS outs
WHERE ins.ANIMAL_ID = outs.ANIMAL_ID
ORDER BY DATEDIFF(outs.DATETIME, ins.DATETIME) DESC
LIMIT 2;


-- solve2
SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS AS ins
JOIN ANIMAL_OUTS AS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
ORDER BY DATEDIFF(outs.DATETIME, ins.DATETIME) DESC
-- ORDER BY DATEDIFF(ins.DATETIME, outs.DATETIME) 위와 동일
LIMIT 2;